export const DUBAI_STANDARDS = {
  parking: {
    ratiosByCategory: {
      Studio: 1,
      "1BR": 1,
      "2BR": 1,
      "3BR": 2,
      "4BR": 2,
      Penthouse: 2,
    },
    prmPercent: 0.02,
    visitorsPercent: 0,
  },
  waste: {
    generationKgPer100sqmPerDay: 12,
    storageDays: 2,
    densityKgPerM3: 150,
    container: { capacityM3: 2.5, widthM: 1.37, lengthM: 2.04 },
    separationM: 0.15,
    frontClearanceM: 0.6,
  },
  lifts: {
    handlingPctStandard: 0.05,
    handlingPctPremium: 0.07,
    unitsPerLiftRule: 75,
    dcdMinLifts: 3,
    dcdMinUnitsThreshold: 100,
    weightPerPerson: 75,
    capacityFactor: 0.8,
    secondsPerStop: 8,
    handlingWindowSec: 300,
  },
  fire: {
    maxTravelDistanceM: 61,
  },
} as const;

/** Suggestions for the "Area / community" field — free text is also accepted. */
export const DUBAI_ZONES = [
  "Al Barsha",
  "Al Furjan",
  "Al Jaddaf",
  "Al Quoz",
  "Al Satwa",
  "Al Sufouh",
  "Al Warsan",
  "Arabian Ranches",
  "Arjan",
  "Barsha Heights (TECOM)",
  "Bluewaters",
  "Bur Dubai",
  "Business Bay",
  "City Walk",
  "Culture Village",
  "DAMAC Hills",
  "DAMAC Hills 2",
  "Deira",
  "Discovery Gardens",
  "Downtown Dubai",
  "Dubai Creek Harbour",
  "Dubai Harbour",
  "Dubai Healthcare City",
  "Dubai Hills Estate",
  "Dubai Investments Park (DIP)",
  "Dubai Islands",
  "Dubai Marina",
  "Dubai Maritime City",
  "Dubai Production City (IMPZ)",
  "Dubai Science Park",
  "Dubai Silicon Oasis",
  "Dubai South",
  "Dubai Sports City",
  "Dubai Studio City",
  "Dubailand",
  "Emaar Beachfront",
  "Expo City",
  "International City",
  "Jebel Ali",
  "Jumeirah",
  "Jumeirah Beach Residence (JBR)",
  "Jumeirah Golf Estates",
  "Jumeirah Lake Towers (JLT)",
  "Jumeirah Park",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Majan",
  "Meydan",
  "Mirdif",
  "Mohammed Bin Rashid City (MBR City)",
  "Motor City",
  "Mudon",
  "Nad Al Sheba",
  "Palm Jumeirah",
  "Ras Al Khor",
  "Remraam",
  "Sobha Hartland",
  "The Valley",
  "Town Square",
  "Umm Suqeim",
  "Zabeel",
];
